### ISSUE TITLE
[USER QUESTION] How to apply JSON encoded profile?

### ISSUE THREAD

**Issue by jluehe** [modheader/modheader_selenium#14]
Is it possible to have modheader_selenium look for a JSON encoded user profile in a default location on the filesystem and apply its settings (e.g., request header names and values to be added), or specify the profile location via some arguments, as in:
```
-u   choose a user profile by name
-f   choose a file location for header definitions
```

**Comment by jluehe** [comment]
@hao1300, do you have any suggestions? Thank you!

**Comment by omarmhaimdat** [comment]
I think you have to do it manually in your selenium program

**Comment by hao1300** [comment]
yea, you have to pass it through the URL. Extensions don't have permissions to read file system or Chrome arguments.
