### ISSUE TITLE
Issues Reusing the Extension in a New Session with the Same Firefox Profile

### ISSUE THREAD

**Issue by omarmhaimdat** [modheader/modheader_selenium#16]
I am using selenium with Firefox, and I use a custom firefox profile where I add the extension to the same profile. The first session goes as expected, the extension does the job. But, when I kill that session and restart a new one, the extension doesn't work at all, I tried to clean the temporary Firefox profile folder, but nothing, I got the same issue. Here is step by step what I do:

1. Create a new Firefox Profile
2. Start a new session with the new Firefox Profile and using Selenium to add the extension file
3. Works perfectly, the information is injected in the request Header as expected.
4. Kill the driver
5. Start a new session with the exact same configuration as in (2)
6. The request headers are not modified

----
Extension Version: 1.0.4
Firefox Version: 84.0.2 (Headless)
Geckodriver Version: 0.28
OS Version: Alpine 3.12.6

**Comment by hao1300** [comment]
It might be an issue with gecko driver. I am not able to reproduce in version 3.0.1 any more.
