### ISSUE TITLE
Modifed Headers always be lowercased

### ISSUE THREAD

**Issue by ChronoBrake** [modheader/modheader_selenium#32]
Hey, i have a little problem.
Some sites are case sensitive. With ModHeader all modifed headers always be lowercase and then server side not detecting that.

Example with ModHeader:
<img width="1414" alt="xsrf1" src="https://user-images.githubusercontent.com/47286873/186026527-b55d13d5-b11d-4fdc-a326-4b7e6ce646fd.PNG">
Example clear:
<img width="1352" alt="xsrf2" src="https://user-images.githubusercontent.com/47286873/186026536-ad7245fc-fdac-4a77-b094-19ba5ffaafce.PNG">

How i can set ModHeader to not lowercase my headers :/
Best Regards

**Comment by hao1300** [comment]
Hi @ChronoBrake, please refer to https://docs.modheader.com/using-modheader/modify-request-headers#why-is-my-request-header-in-lower-case regarding this issue.
