### ISSUE TITLE
How to load two profiles via api?

### ISSUE THREAD

**Issue by ChronoBrake** [modheader/modheader_selenium#34]
Hey Sir i trying to load profiles via /load and its working fine for 1 profile, but when i trying to upload json with more 1 profiles its crashing extenstion. I do something wrong or it's not supported by extension. I see in normal way (click in popup) i can export multiple profiles by checking boxes, but load via /load api not working.

Examples:
site: https://webdriver.modheader.com/load
1 profile working fine:
https://pastebin.com/raw/7EVfrA5w
2 profiles not working after load:
https://pastebin.com/raw/UYnUYXa6

Best Regards

**Comment by ChronoBrake** [comment]
ohh i see in documentation:

`exported_profile_in_json can be obtained from the regular ModHeader extension using ... -> Export Profile. Note that ModHeader exports an array of profiles by default, but this API will only accept a single profile, so you will need to extract the profile you want from the array and pass it in.`

Any ETA when API will support load multiple profiles? It's will be awesome for devs :/

**Comment by hao1300** [comment]
@ChronoBrake - Can you try again with the latest version. The API now supports both a single profile as well as an array of profile.

**Comment by ChronoBrake** [comment]
> @ChronoBrake - Can you try again with the latest version? The API now supports both a single profile as well as an array of profile.

Working perfectly <3
