### ISSUE TITLE
Broken in Chrome 109?

### ISSUE THREAD

**Issue by ndtreviv** [modheader/modheader_selenium#42]
I just updated to Chrome 109 today and this broke. Now I get:

```
15:08:27.916 [Test worker] WARN com.cameraforensics.sitefingerprinting.services.FeatureExtractorService - Couldn't prepare the webdriver: Could not start a new session. Response code 500. Message: unknown error: failed to wait for extension background page to load: chrome-extension://jciacimpfapbkckkegdfngcnbdpabaoi/_generated_background_page.html
```

again. WebDriver options being used are:

```
    public static final List<String> DEFAULT_WEBDRIVER_PROPERTIES = Arrays.asList(
            "--kiosk",
            "--headless=chrome",
            "--disable-dev-shm-usage",
            "--ignore-certificate-errors",
            "--disable-blink-features=AutomationControlled",
            "--log-level=DEBUG",
            "--whitelisted-ips",
            "--disable-gpu",
            "--disable-software-rasterizer",
            "--verbose"
    );
```

When I run it not-headless it all works just fine.

If I run it not-headless, and go to the extension itself and try to view the background page the link to the background page under `Inspect views` does nothing (nothing happens when you click it):

<img width="1207" alt="Screenshot 2023-01-24 at 15 11 09" src="https://user-images.githubusercontent.com/1530653/214331712-0cf2ac46-e741-4e4c-b52b-02ba7fb9f4ee.png">

Interestingly, if I take off headless mode, put in a breakpoint and go to chrome-extension://jciacimpfapbkckkegdfngcnbdpabaoi/_generated_background_page.html it literally takes me no-where - the page stays blank.

**Comment by hao1300** [comment]
@ndtreviv can you try using `--headless=new` instead?

**Comment by ndtreviv** [comment]
That works 👍 Thanks!

**Comment by ndtreviv** [comment]
Will this work on older versions of Chrome as well? Just thinking about dev environment vs... etc

**Comment by hao1300** [comment]
@ndtreviv I am not sure. You may want to ask the Chromium / Chrome Web Driver team about it. I don't know why they decided on this...

**Comment by sarojlucky** [comment]
if we dont pass modheader.crx in chrome options it works with headless=chrome if we pass modeheader.crx we need to change it to headless=new.
 
Is the a code break in modheader side or chrome side?
how headless= parameter is related to modheader.crx file? 
can you provide some more info on this?

**Comment by ndtreviv** [comment]
> if we dont pass modheader.crx in chrome options it works with headless=chrome if we pass modeheader.crx we need to change it to headless=new.

Is that correct? I get the impression that v107 is `headless=chrome` and v109 is `headless=new` regardless of the application of modheader. It sounds like Chromeium/Chrome team have made that change

**Comment by ndtreviv** [comment]
Closing because this issue is fixed.

**Comment by hao1300** [comment]
@sarojlucky @ndtreviv - this is a Chromium change. `--headless=new` is needed in Chrome v109 for any extension installation in WebDriver headless mode. It is independent of ModHeader.

**Comment by sarojlucky** [comment]
okay, thanks @hao1300
