### ISSUE TITLE
modheader for chrome didn't work for webdriverio

### ISSUE THREAD

**Issue by AlfredoMoretta** [modheader/modheader_selenium#43]
good morning,
i followed the doc here https://docs.modheader.com/advanced/selenium-webdriver but didn't work for me.
I'm using webdriverio v.7 and this is my wdio.conf.js

`const path = require('path');
const chromeModheader = require('chrome-modheader');
const JOB_ID = process.env.JOB_ID || 'dummyLocal';
const CustomReporter = require('./test/utils/customReporter');
const { suites } = require('./test-suites.conf');
const { hooks } = require('./hooks');

exports.config = {
    services: ['devtools'],
    /* Specify Test Files */
    specs: ['./test/features/**/*.feature'],
    /* Define specific suites */
    suites,
    /* Capabilities */
    maxInstances: 1,
    acceptInsecureCerts: true,
    capabilities: [
        {
            browserName: 'chrome',
            'goog:chromeOptions': {
                extensions: [chromeModheader.getEncodedExtension()],
                args: [
                    // '--headless',
                    '--no-sandbox',
                    '--incognito',
                    // '--start-fullscreen',
                    '--disable-notifications',
                ],
                prefs: {
                    /*
                        0 ==> default
                        1 ==> Allow
                        2 ==> Block
                    */
                    // 'profile.managed_default_content_settings.javascript': 2,
                    // 'profile.managed_default_content_settings.images': 2,
                    'profile.default_content_setting_values.notifications': 2,
                    // 'profile.managed_default_content_settings.stylesheets':2,
                    // 'profile.managed_default_content_settings.cookies': 2,
                    'profile.managed_default_content_settings.plugins': 2,
                    'profile.managed_default_content_settings.popups': 2,
                    'profile.managed_default_content_settings.geolocation': 2,
                    'profile.managed_default_content_settings.media_stream': 2,
                },
            },
        },
    ],
    before: function () {
        browser.url(chromeModheader.getAddHeaderUrl('here i put name of the header', 'here i put value of the header'));
    },
    /* Level of logging verbosity: trace | debug | info | warn | error | silent */
    logLevel: 'debug',
    outputDir: path.join(__dirname, '/logs'),
    coloredLogs: true, // Enables colors for log output.
    sync: true,
    bail: 0,
    baseUrl: '', //baseUrl is not used because it is overridden by browser.url() in Common.page.js
    waitforTimeout: 200000,
    connectionRetryTimeout: 200000,
    connectionRetryCount: 3,
    framework: 'cucumber',
    reporters: [
        'spec',
        [
            'cucumberjs-json',
            {
                jsonFolder: `reports/${JOB_ID}`,
                language: 'en',
            },
        ],
        CustomReporter,
    ],
    cucumberOpts: {
        requireModule: [],
        require: ['./test/step-definitions/*.js'],

        // <boolean> show full backtrace for errors
        backtrace: false,

        // <boolean> invoke formatters without executing steps
        dryRun: false,

        // <boolean< Treat ambiguous definitions as errors
        failAmbiguousDefinitions: true,

        // <boolean> abort the run on first failure
        failFast: false,

        // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
        format: ['pretty'],

        // <boolean> disable colors in formatter output
        colors: true,

        // <boolean> hide step definition snippets for pending steps
        snippets: true,

        // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        name: [],

        // <boolean> hide source uris
        source: false,

        // <string[]> (name) specify the profile to use
        profile: [],

        // <boolean> fail if there are any undefined or pending steps
        strict: true,

        // <string> (expression) only execute the features or scenarios with tags matching the expression
        tagExpression: 'not @pending',

        // <boolean> add cucumber tags to feature or scenario name
        tagsInTitle: false,

        // <number> timeout for step definitions
        timeout: 300000,

        // <boolean> Enable this config to treat undefined definitions as warnings.
        ignoreUndefinedDefinitions: false,

        // <string> specify a custom snippet syntax
        snippetSyntax: undefined,

        // Specify the number of times to retry failing test cases
        retry: 2,

        //Inserts WebdriverIO's globals (e.g. `browser`, `$` and `$$`) into the global environment.
        injectGlobals: true,
    },
    /* Cucumber-specific hooks */
    ...hooks,
    // onPrepare(),
    // onComplete(),
};`

i didn' have any type of error but didn't work correctly.Could you help please?

**Comment by dlitmano** [comment]
const chromeModheader = require("chrome-modheader"); <- import

inside chrome options:
          extensions: [chromeModheader.getEncodedExtension()],   

 before: async function () {
      await browser.url(
        chromeModheader.getAddHeaderUrl(
          { "Test-Agent": "Test" }
        )
      );
    },

**Comment by dlitmano** [comment]
please share you repo on github, to reproduce

**Comment by AlfredoMoretta** [comment]
@dlitmano thank you for the answer,
i try with async(it's the only thing that differ from what i posted). I can't actually share a git hub repo for reproduce the issue

**Comment by AlfredoMoretta** [comment]
put async/await  as you suggested unfortunately didn't change anything.

**Comment by dlitmano** [comment]
try without spaces inside the object

**Comment by dlitmano** [comment]
or try this https://webdriver.modheader.com/add?{header_name}={header_value}

**Comment by AlfredoMoretta** [comment]
are you sure you can pass an header like a query string? doesn't work for me

**Comment by AlfredoMoretta** [comment]
i can add that i always have this page when i start my automatic test.I try to remove all node_modules and reinstall but nothing change.
<img width="1199" alt="Screenshot 2023-03-02 at 13 13 31" src="https://user-images.githubusercontent.com/13521031/222426051-2411ae90-c8a1-45ca-9c3c-ab7c69f1dab3.png">

**Comment by dlitmano** [comment]
are you using the latest versions on webdriverio and modheader?

**Comment by AlfredoMoretta** [comment]
this is my package.json

 "dependencies": {
        "@babel/cli": "7.12.1",
        "@babel/core": "7.12.3",
        "@babel/preset-env": "7.12.1",
        "@babel/register": "7.12.1",
        "@wdio/allure-reporter": "^7.24.0",
        "@wdio/cli": "^7.24.0",
        "@wdio/codemod": "^0.12.0",
        "@wdio/cucumber-framework": "^7.24.0",
        "@wdio/devtools-service": "^7.25.2",
        "@wdio/local-runner": "^7.24.0",
        "@wdio/reporter": "7.25.1",
        "@wdio/selenium-standalone-service": "^7.24.0",
        "@wdio/spec-reporter": "^7.24.0",
        "@wdio/sync": "^7.24.0",
        "cheerio": "^1.0.0-rc.12",
        "chrome-modheader": "^2.0.3",
        "chromedriver": "^109.0.0",
        "cucumber-html-reporter": "5.2.0",
        "jscodeshift": "^0.13.1",
        "pactum": "^3.3.1",
        "request": "2.88.2",
        "wdio-chromedriver-service": "^7.3.2",
        "wdio-cucumberjs-json-reporter": "4.4.3",
        "webdriverio": "^7.24.0"

**Comment by hao1300** [comment]
@AlfredoMoretta - I tried using your wdio.conf.js to run my test and it is working for me. The most likely issue is probably in the browser. Please try this:
- Pause the execution of the test at webdriver.modheader.com, and go to `chrome://extensions`. See if ModHeader extension is installed there. If not that means that installation has failed.
- If ModHeader extension is there, then enable Developer mode, and click on the "background_page" link. Go to the console and see if there is any error there.
- If there are no errors there, then try to open up ModHeader popup. Does it open? If not, right click on the ModHeader icon and select "Inspect popup". See if there are any errors there. If so, please share it here.
- If the popup opens, please try to add a header manually, and see if the header modification works. You can use our tool https://modheader.com/headers to check the header. Let's us know if the manual header modification works.

Finally, please share your browser version and OS version.

**Comment by AlfredoMoretta** [comment]
@hao1300 first of all thank you for the answer.I've checked all your points and i had no problems with adding headers with modheader manually (works perfectly).I've this issue only with automatic tests.

Update: i found the problem and maybe i think can help adding this information to your documentation. 
the problem was that i run my new test always with chrome with --incognito. without the incognito mode seams to work as we expected.

Thank you for all your support guys.
