### ISSUE TITLE
Title timeout error

### ISSUE THREAD

**Issue by srshkmr** [modheader/modheader_selenium#44]
Error : 
```
Wait timed out after 10201ms
at exit (/codebuild/output/src381708701/src/node_modules/@cucumber/cucumber/lib/runtime/parallel/run_worker.js:12:54)
at /codebuild/output/src381708701/src/node_modules/@cucumber/cucumber/lib/runtime/parallel/run_worker.js:25:31
at processTicksAndRejections (node:internal/process/task_queues:96:5)
caused by: VError: a BeforeAll hook errored on worker 3, process exiting: features/support/hooks.js:13: Waiting for title to be "Done"
```

Browser configuration:
```
let webdriver = require('selenium-webdriver');
let chrome = require('selenium-webdriver/chrome');
const {getExtension, getAddHeaderUrl} = require("chrome-modheader");
const {until} = require("selenium-webdriver");

const screen = {
    width: 1920,
    height: 1080
};
const buildBrowser = () => {
    var chromeoptions = new chrome.Options();
    chromeoptions.addArguments("headless=new");
    chromeoptions.addArguments("start-maximized"); // open Browser in maximized mode
    chromeoptions.addArguments("disable-infobars"); // disabling infobars
    chromeoptions.addArguments("--disable-dev-shm-usage"); // overcome limited resource problems
    chromeoptions.addArguments("--no-sandbox"); // Bypass OS security model
    chromeoptions.addArguments("--enable-javascript");
    chromeoptions.addExtensions(getExtension());
    return new webdriver.Builder().forBrowser('chrome')
        .setChromeOptions(chromeoptions.windowSize(screen))
        .build();

const setupBrowser = async (driver) => {
    await driver.get(getAddHeaderUrl('my-header', 'my-framework'));
    await driver.wait(until.titleIs('Done'), 10000);
    await driver.manage().window().maximize();
    await driver.manage().deleteAllCookies();
}
```

Chrome Driver version: `ChromeDriver 111.0.5563.64`
Google Chrome version: `Google Chrome 111.0.5563.146`

Same issue happened with `ChromeDriver 109.0.5414.74` as well.

Any suggestions on how to resolve this issue?

**Comment by hao1300** [comment]
@srshkmr - can you follow the instructions here to gather more info? https://docs.modheader.com/advanced/selenium-webdriver#faq

That is, can you check the followings:
1, ModHeader extension has been installed properly in WebDriver
2, Any error log you see in the ModHeader extension's background page

**Comment by srshkmr** [comment]
hi @hao1300  So this is what is happening.

I can see the following page for a second 
![image](https://user-images.githubusercontent.com/8898147/229499437-f48b4a65-bec3-4d5d-a5eb-e7b61033a545.png)

and then when the page redirects to add the header I get the following

![image](https://user-images.githubusercontent.com/8898147/229499104-21765714-94a6-45c9-a772-783424aeaec1.png)

Going back and hitting the developer mode and clicking on the background page i don't see any errors in the console.

![image](https://user-images.githubusercontent.com/8898147/229499298-ad19c434-d731-4615-83f2-95716e3d3d8b.png)

**Comment by hao1300** [comment]
@srshkmr - I am afraid I don't see anything obvious here. Can you schedule something with me https://calendly.com/modheader/30min so we can debug this together?

**Comment by hao1300** [comment]
@srshkmr - are you joining the meeting?

**Comment by hao1300** [comment]
@srshkmr - It is past our scheduled debugging time and I don't see you joining. Unfortunately I cannot help you further on this if you do not show up.

Here are my suggestions for you to self debug further:
1, Try running your test against Firefox webdriver and see if it works. If it works in Firefox but not in Chrome, then it is browser specific issue, and you may want to reach out to Chromium team for help.
2, Ask your colleague to run the test and see if works on their computer.
3, Try running the example tests in this repo and see if they work for you.
4, Pause your webdriver run and open up the ModHeader popup. See if you can make modification there. Check if those modifications are getting applied. If the mods do not show up, or the modifications do not work, check the extension background page to see if there are any error logs. Also right click on the ModHeader extension popup icon and click on Inspect popup. See if there are any error logs there.
